/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./MyPortfolio/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0b1326",
        "surface-tint": "#c0c1ff",
        "surface-container-highest": "#2d3449",
        "tertiary-fixed-dim": "#ffb783",
        "on-primary-fixed": "#07006c",
        "on-surface": "#dae2fd",
        "on-primary-container": "#0d0096",
        secondary: "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed-variant": "#404178",
        "surface-variant": "#2d3449",
        tertiary: "#ffb783",
        "on-surface-variant": "#c7c4d7",
        "tertiary-fixed": "#ffdcc5",
        error: "#ffb4ab",
        "surface-bright": "#31394d",
        "inverse-primary": "#494bd6",
        "secondary-container": "#42447b",
        "on-error-container": "#ffdad6",
        "primary-container": "#8083ff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#703700",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#d97721",
        "on-secondary-container": "#b2b3f2",
        "on-secondary-fixed": "#13144a",
        "on-secondary": "#292a60",
        outline: "#908fa0",
        primary: "#c0c1ff",
        "on-error": "#690005",
        "on-primary": "#1000a9",
        "error-container": "#93000a",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "on-tertiary-fixed": "#301400",
        background: "#0b1326",
        "outline-variant": "#464554",
        "on-tertiary": "#4f2500",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-background": "#dae2fd",
        "surface-container": "#171f33",
        surface: "#0b1326",
        "inverse-on-surface": "#283044",
        "surface-container-low": "#131b2e",
        "on-tertiary-container": "#452000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
